### ISSUE TITLE
News Broker - kafka connect Error 

### ISSUE THREAD

**Issue by stellakang** [sr-sig3/news-stream-broker#4]
## Kafka Broker 
docker-compose.yml

```yml
version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - kafka-network

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    depends_on:
      - zookeeper
    networks:
      - kafka-network

  kafdrop:
    image: obsidiandynamics/kafdrop:3.30.0
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: kafka:9092
      JVM_OPTS: "-Xms32M -Xmx64M"
    depends_on:
      - kafka
    networks:
      - kafka-network

networks:
  kafka-network:
    driver: bridge 

```

**Comment by stellakang** [comment]
## Data Collector

docker-compose.yml

```yml
version: '3.8'

services:
  news-collector:
    build: .
    container_name: news_collector
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS:-kafka:9092}
      - KAFKA_TOPIC=${KAFKA_TOPIC:-news-topic}
      - NAVER_CLIENT_ID=${NAVER_CLIENT_ID}
      - NAVER_CLIENT_SECRET=${NAVER_CLIENT_SECRET}
    networks:
      - news-network
      - news-stream-broker_kafka-network

networks:
  news-network:
    driver: bridge
  news-stream-broker_kafka-network:
    name: news-stream-broker_kafka-network
    external: true 
```

**Comment by stellakang** [comment]
## Data Processor

docker-compose.yml

```yml
version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: news_db
    environment:
      POSTGRES_DB: news_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres  # 실제 운영 환경에서는 더 강력한 비밀번호 사용
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - news-network

  news-processor:
    build: .
    container_name: news_processor
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/news_db
      - KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS:-kafka:9092}
      - KAFKA_TOPIC=${KAFKA_TOPIC:-news-topic}
      - KAFKA_GROUP_ID=${KAFKA_GROUP_ID:-news-processor-group}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - news-network
      - news-stream-broker_kafka-network

networks:
  news-network:
    driver: bridge
  news-stream-broker_kafka-network:
    name: news-stream-broker_kafka-network
    external: true

volumes:
  postgres_data:

```
